// Central trek data — served statically during dev.
// In production, swap with API calls to /api/treks

export const TREKS = [
  {
    _id: '1',
    slug: 'kedarkantha',
    name: 'Kedarkantha',
    region: 'Uttarakhand',
    state: 'Uttarakhand',
    difficulty: 'Easy',
    duration: 6,
    maxAltitude: 3950,
    maxAltitudeFt: 12966,
    price: 8500,
    featured: true,
    shortDesc: 'A perfect winter summit offering 360° views of Himalayan giants from Swargarohini to Ranglana.',
    description: 'Kedarkantha is one of the most beautiful winter treks in India, located in the Govind Wildlife Sanctuary. The trek rewards you with stunning views of Swargarohini, Bandarpoonch, Kalanag, Ranglana, and several other Himalayan giants from its summit.',
    highlights: [
      'Summit panorama of 13 Himalayan peaks',
      'Spectacular snow-covered pine forests',
      'Four beautiful campsite meadows',
      'Perfect introduction to winter trekking',
      'Traditional Himalayan villages en route'
    ],
    images: [
      { url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782282445/treks/kedarkantha/kndgasf92iqmhw8fqwr1.jpg', caption: 'Kedarkantha summit view' },
      { url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782282446/treks/kedarkantha/z077yikfcenbufybxecx.jpg', caption: 'Kedarkantha trail' },
      { url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782282448/treks/kedarkantha/atgysj3clnmmtog3nmly.jpg', caption: 'Kedarkantha campsite' },
      { url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782282449/treks/kedarkantha/kkqcamenob5vsru5kfw2.jpg', caption: 'Kedarkantha winter landscape' },
      { url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782282449/treks/kedarkantha/bfaawufuxg1fitpyg9g2.jpg', caption: 'Kedarkantha base camp' },
    ],
    bestSeason: ['November', 'December', 'January', 'February', 'March', 'April'],
    elevationProfile: [
      { km: 0, altM: 2400 }, { km: 4, altM: 2700 }, { km: 9, altM: 3100 },
      { km: 14, altM: 3400 }, { km: 18, altM: 3700 }, { km: 21, altM: 3950 },
      { km: 26, altM: 3100 }, { km: 30, altM: 2400 }
    ],
    mapImage: '/assets/mapes/kedarkanttha.png',
    itinerary: [
      { day: 1, title: 'Dehradun to Kotgaon', description: 'Drive: 195 km • 10–11 hrs | Begin your journey with a scenic drive from Dehradun to Kotgaon, the trek’s base camp. Enjoy beautiful mountain roads, rivers, and charming Himalayan villages along the way.' },
      { day: 2, title: 'Kotgaon to Khujaai', description: 'Trek: 5.3 km • 5 hrs | Altitude: 6,400 ft → 9,460 ft | The trail gradually climbs through dense pine and oak forests before reaching the peaceful campsite of Khujaai.' },
      { day: 3, title: 'Khujaai to Bhoja Dhadi', description: 'Trek: 3 km • 3.5 hrs | Altitude: 9,460 ft → 10,700 ft | A short yet rewarding trek through alpine landscapes leads to Bhoja Dhadi, offering stunning mountain views and tranquil surroundings.' },
      { day: 4, title: 'Bhoja Dhadi → Kedarkantha Summit → Khujaai', description: 'Trek: 9 km • 7–8 hrs | Summit: 12,500 ft | Today’s summit push rewards you with breathtaking 360° views of the Garhwal Himalayas before descending back to Khujaai for the night.' },
      { day: 5, title: 'Khujaai to Kotgaon', description: 'Trek: 5.3 km • 4–5 hrs | Altitude Loss: 9,460 ft → 6,400 ft | Descend through scenic forests back to Kotgaon, where the trek concludes with an overnight stay at the base camp.' },
      { day: 6, title: 'Kotgaon to Dehradun', description: 'Drive: 195 km • 10–11 hrs | After breakfast, drive back to Dehradun, carrying unforgettable memories of the Kedarkantha adventure.' }
    ],
    inclusions: ['Accommodation (camping/guesthouse)', 'All meals on trek', 'Expert trek leader', 'Safety equipment', 'Forest permits', 'First aid kit'],
    exclusions: ['Travel to Dehradun', 'Personal gear', 'Travel insurance', 'Tips'],
    avgRating: 4.8,
  },
  {
    _id: '2',
    slug: 'valley-of-flowers',
    name: 'Valley of Flowers',
    region: 'Uttarakhand',
    state: 'Uttarakhand',
    difficulty: 'Easy',
    duration: 6,
    maxAltitude: 3658,
    maxAltitudeFt: 12000,
    price: 9000,
    featured: true,
    shortDesc: 'UNESCO World Heritage Site bursting with 500+ species of wildflowers, surrounded by Himalayan peaks.',
    description: 'The Valley of Flowers National Park, a UNESCO World Heritage Site, is a high-altitude Himalayan valley covered in alpine flowers of unimaginable variety. The valley blooms from July to September with over 500 species of wildflowers.',
    highlights: [
      'UNESCO World Heritage Site',
      '500+ species of wildflowers',
      'Pristine Himalayan meadows',
      'Hem Kund Sahib nearby',
      'Rich wildlife including Snow Leopard'
    ],
    images: [
      { url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782282755/treks/valley-of-flowers/r3jvcdxuohkue2uw0r24.jpg', caption: 'Valley of Flowers banner' },
      { url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782282756/treks/valley-of-flowers/ofdyhwfac271ar3b9ki3.jpg', caption: 'Valley of Flowers landscape' },
      { url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782282757/treks/valley-of-flowers/jsbtwkcovimk8lnlrt2f.jpg', caption: 'Valley of Flowers trail' },
      { url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782282758/treks/valley-of-flowers/hbzkwg1rg6mxwci0p2ti.jpg', caption: 'Valley of Flowers flora' },
      { url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782282759/treks/valley-of-flowers/y0hqtpcvtrn5j0mh0n3v.jpg', caption: 'Valley of Flowers scenic view' },
      { url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782282760/treks/valley-of-flowers/e5t3qwhckhqdlkzjr3ew.jpg', caption: 'Valley of Flowers mountains' },
    ],
    bestSeason: ['July', 'August', 'September'],
    elevationProfile: [
      { km: 0, altM: 1800 }, { km: 5, altM: 2200 }, { km: 10, altM: 2600 },
      { km: 15, altM: 3000 }, { km: 19, altM: 3200 }, { km: 22, altM: 3658 }
    ],
    mapImage: '/assets/mapes/vally-of-flower.png',
    itinerary: [
      { day: 1, title: 'Rishikesh → Karchi', description: 'Drive: 255 km • 11 hrs' },
      { day: 2, title: 'Karchi → Poolna (Drive) → Ghangaria (Trek)', description: 'Drive: 38 km • 1.5 hrs | Trek: 9 km • 5–6 hrs | Altitude: 7,785 ft → 10,520 ft' },
      { day: 3, title: 'Ghangaria → Valley of Flowers → Ghangaria', description: 'Trek: 3.7 km (each way) • 6 hrs | Altitude: 10,520 ft → 11,550 ft' },
      { day: 4, title: 'Ghangaria → Hemkund Sahib → Ghangaria', description: 'Trek: 6 km (each way) • 8–9 hrs | Altitude: 10,520 ft → 14,107 ft' },
      { day: 5, title: 'Ghangaria → Poolna (Trek) → Karchi (Drive)', description: 'Trek: 9 km • 4 hrs | Drive: 38 km • 1 hr 15 min' },
      { day: 6, title: 'Karchi → Rishikesh', description: 'Drive: 255 km • 9–10 hrs' }
    ],
    inclusions: ['Accommodation', 'All meals on trek', 'Certified guide', 'National Park permit', 'Safety equipment'],
    exclusions: ['Travel to Rishikesh', 'Personal expenses', 'Travel insurance'],
    avgRating: 4.9,
  },
  {
    _id: '3',
    slug: 'hampta-pass',
    name: 'Hampta Pass',
    region: 'Himachal Pradesh',
    state: 'Himachal Pradesh',
    difficulty: 'Moderate',
    duration: 5,
    maxAltitude: 4270,
    maxAltitudeFt: 14009,
    price: 12000,
    featured: true,
    shortDesc: 'A dramatic crossover trek from the lush green Kullu valley to the stark moon landscape of Lahaul.',
    description: 'Hampta Pass offers one of the most dramatic contrasts in Himachal Pradesh — transitioning from the lush, green Kullu valley to the stark, arid moonscapes of Lahaul. The crossing at 4270m offers jaw-dropping views.',
    highlights: [
      'Stunning contrast of Kullu & Lahaul valleys',
      'Chandratal Lake day trip option',
      'Challenging yet achievable river crossings',
      'Views of Deo Tibba and Indrasan peaks',
      'Stark beauty of Lahaul moonscapes'
    ],
    images: [
      { url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782291402/treks/hampta-pass/f5xacx0blqjqa2cclk7i.jpg', caption: 'Hampta Pass banner' },
      { url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782291404/treks/hampta-pass/sqs13djsw1xm97cebnob.jpg', caption: 'Hampta Pass trail' },
      { url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782291405/treks/hampta-pass/eihcekewetnyeqizwp5s.jpg', caption: 'Hampta Pass landscape' },
      { url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782291407/treks/hampta-pass/au6jaoclevenfgfwc5n2.jpg', caption: 'Hampta Pass view' },
      { url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782291408/treks/hampta-pass/ynyt3im16vuyfj6hzg7s.jpg', caption: 'Hampta Pass crossing' },
      { url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782291409/treks/hampta-pass/rs1pymicla8fnr06gwwp.jpg', caption: 'Hampta Pass scenery' },
    ],
    bestSeason: ['June', 'July', 'August', 'September'],
    elevationProfile: [
      { km: 0, altM: 2480 }, { km: 4, altM: 2800 }, { km: 8, altM: 3100 },
      { km: 13, altM: 3600 }, { km: 17, altM: 4270 }, { km: 22, altM: 3700 },
      { km: 27, altM: 3200 }
    ],
    itinerary: [
      { day: 1, title: 'Manali to Chika', description: 'Drive to Jobra, then trek through dense deodar forests to Chika meadow.', campAltitude: 3100 },
      { day: 2, title: 'Chika to Balu Ka Ghera', description: 'Gradual climb through open meadows with views of Deo Tibba.', campAltitude: 3636 },
      { day: 3, title: 'Balu Ka Ghera to Shea Goru via Pass', description: 'Cross Hampta Pass (4270m) and descend into the spectacular Lahaul valley.', campAltitude: 3900 },
      { day: 4, title: 'Shea Goru to Chatru & Return', description: 'Descend to Chatru and drive to Manali, passing Chandratal Lake.', campAltitude: 0 }
    ],
    inclusions: ['Camping accommodation', 'All meals', 'Trek leader', 'Permits', 'Safety equipment'],
    exclusions: ['Travel to Manali', 'Personal expenses', 'Chandratal Lake visit (optional)'],
    avgRating: 4.7,
  },
  {
    _id: '4',
    slug: 'rupin-pass',
    name: 'Rupin Pass',
    region: 'Uttarakhand',
    state: 'Uttarakhand',
    difficulty: 'Moderate',
    duration: 8,
    maxAltitude: 4650,
    maxAltitudeFt: 15300,
    price: 14000,
    featured: false,
    shortDesc: 'One of India\'s most beautiful treks, featuring a dramatic snow wall and a stunning waterfall cascade.',
    description: 'Rupin Pass trek is rated one of the most beautiful treks in India. Its defining feature is the dramatic Rupin waterfall that cascades from snow-covered heights, and the iconic snow wall ascent to the pass at 4650m.',
    highlights: [
      'Iconic Rupin waterfall cascade',
      'Dramatic snow wall ascent',
      'Ancient hanging villages',
      'Unspoilt meadows and pine forests',
      'Stunning Himalayan panoramas'
    ],
    images: [{ url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782209546/treks/lkryvlrdced02uedn5j7.jpg', caption: 'The famous Rupin Pass snow wall' }],
    bestSeason: ['May', 'June', 'September', 'October'],
    elevationProfile: [
      { km: 0, altM: 1525 }, { km: 6, altM: 2100 }, { km: 12, altM: 2500 },
      { km: 18, altM: 3100 }, { km: 23, altM: 3600 }, { km: 28, altM: 4200 },
      { km: 31, altM: 4650 }, { km: 37, altM: 3800 }, { km: 43, altM: 3200 }
    ],
    itinerary: [
      { day: 1, title: 'Dhaula to Sewa', description: 'Drive to Dhaula and trek to Sewa village through terraced fields.', campAltitude: 1690 },
      { day: 2, title: 'Sewa to Jiskun', description: 'Trek through Rupin gorge with stunning views of the waterfall.', campAltitude: 2100 },
      { day: 3, title: 'Jiskun to Udaknal', description: 'Dramatic section with the Rupin waterfall in full view.', campAltitude: 2600 },
      { day: 4, title: 'Udaknal to Upper Waterfall Camp', description: 'Trek past the Rupin falls to camp below the snow bowl.', campAltitude: 3500 },
      { day: 5, title: 'Upper Waterfall to Snow Bridge', description: 'Traverse the iconic snow wall to reach the snow bridge camp.', campAltitude: 4100 },
      { day: 6, title: 'Snow Bridge to Pass to Ronti Gad', description: 'Cross Rupin Pass (4650m) and descend to Ronti Gad.', campAltitude: 3500 },
      { day: 7, title: 'Ronti Gad to Sangla', description: 'Descend through beautiful Sangla valley forests to Sangla village.', campAltitude: 2680 }
    ],
    inclusions: ['All camping accommodation', 'Meals on trek', 'Expert guide', 'Permits & fees', 'Safety gear'],
    exclusions: ['Travel to Dhaula', 'Personal trekking gear', 'Insurance'],
    avgRating: 4.8,
  },
  {
    _id: '5',
    slug: 'roopkund',
    name: 'Roopkund',
    region: 'Uttarakhand',
    state: 'Uttarakhand',
    difficulty: 'Hard',
    duration: 8,
    maxAltitude: 5029,
    maxAltitudeFt: 16499,
    price: 16500,
    featured: false,
    shortDesc: 'The Skeleton Lake — a mysterious glacial lake at 5029m surrounded by ancient human skeletal remains.',
    description: 'Roopkund, also known as the Mystery Lake or Skeleton Lake, lies hidden in the Trishul massif at 5029m. The lake contains hundreds of ancient human skeletons on its edge, adding an eerie mystique to an already dramatic high-altitude trek.',
    highlights: [
      'The mysterious Skeleton Lake at 5029m',
      'Views of Trishul and Nanda Ghunti',
      'Ancient bugyal (meadow) at Ali Bugyal',
      'Oak and rhododendron forests',
      'One of India\'s most dramatic treks'
    ],
    images: [{ url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782209548/treks/gnjaxtffpplrnhqcnbfl.jpg', caption: 'The eerie Roopkund lake surrounded by snow' }],
    bestSeason: ['May', 'June', 'September', 'October'],
    elevationProfile: [
      { km: 0, altM: 2200 }, { km: 7, altM: 2600 }, { km: 13, altM: 3100 },
      { km: 18, altM: 3550 }, { km: 22, altM: 4000 }, { km: 27, altM: 4500 },
      { km: 30, altM: 5029 }, { km: 37, altM: 3100 }
    ],
    itinerary: [
      { day: 1, title: 'Lohajung to Didna Village', description: 'Trek through terraced fields and oak forests to Didna village.', campAltitude: 2640 },
      { day: 2, title: 'Didna to Ali Bugyal', description: 'Steep climb through rhododendron forests to the vast Ali Bugyal meadow.', campAltitude: 3612 },
      { day: 3, title: 'Ali Bugyal to Bedni Bugyal', description: 'Trek across beautiful high altitude meadows with Trishul dominating the skyline.', campAltitude: 3354 },
      { day: 4, title: 'Bedni to Pathar Nachauni', description: 'Gradual ascent through increasingly barren landscape.', campAltitude: 4235 },
      { day: 5, title: 'Pathar Nachauni to Bhagwabasa', description: 'Trek to high camp at the base of the final push to Roopkund.', campAltitude: 4780 },
      { day: 6, title: 'Roopkund Summit & Return to Bedni', description: 'Early morning push to Roopkund lake, then long descent back to Bedni.', campAltitude: 3354 },
      { day: 7, title: 'Bedni Bugyal to Lohajung', description: 'Final descent back to Lohajung through dense forests.', campAltitude: 2270 }
    ],
    inclusions: ['All accommodation', 'Meals', 'Certified high-altitude guide', 'All permits', 'Safety & first aid'],
    exclusions: ['Transport to Lohajung', 'Personal gear', 'Altitude sickness medication', 'Insurance'],
    avgRating: 4.6,
  },
  {
    _id: '6',
    slug: 'goechala',
    name: 'Goechala',
    region: 'Sikkim',
    state: 'Sikkim',
    difficulty: 'Hard',
    duration: 11,
    maxAltitude: 4940,
    maxAltitudeFt: 16207,
    price: 22000,
    featured: false,
    shortDesc: 'Closest view of Kangchenjunga — the world\'s third highest peak — from Goechala in Sikkim.',
    description: 'The Goechala trek in Sikkim offers the closest accessible viewpoint of Kangchenjunga (8586m), the world\'s third-highest mountain. Trekking through the Kanchenjunga National Park, the trail passes through diverse ecosystems and ancient monasteries.',
    highlights: [
      'Closest view of Kangchenjunga (8586m)',
      'Stunning high-altitude lakes',
      'Ancient Buddhist monasteries',
      'Diverse ecosystems from subtropical to alpine',
      'Rich wildlife — Red Panda, Himalayan Black Bear'
    ],
    images: [{ url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782209550/treks/nhemf5vxrmqk0xs2ru1a.jpg', caption: 'Kangchenjunga at sunrise from Goechala' }],
    bestSeason: ['April', 'May', 'October', 'November'],
    elevationProfile: [
      { km: 0, altM: 1800 }, { km: 8, altM: 2200 }, { km: 15, altM: 2700 },
      { km: 22, altM: 3300 }, { km: 30, altM: 3900 }, { km: 37, altM: 4400 },
      { km: 40, altM: 4940 }, { km: 48, altM: 3300 }, { km: 55, altM: 1800 }
    ],
    itinerary: [
      { day: 1, title: 'Yuksom to Sachen', description: 'Trek from the historic capital of Sikkim through forest to Sachen.', campAltitude: 2400 },
      { day: 2, title: 'Sachen to Tshoka', description: 'Steep climb through rhododendron and magnolia forest.', campAltitude: 3050 },
      { day: 3, title: 'Tshoka to Dzongri', description: 'Dramatic landscape opens up with first views of Kanchenjunga.', campAltitude: 4030 },
      { day: 4, title: 'Dzongri Top Sunrise & Onward to Thansing', description: 'Pre-dawn hike for sunrise views, then descent to Thansing.', campAltitude: 3930 },
      { day: 5, title: 'Thansing to Samiti Lake', description: 'High altitude lake with crystal reflections of surrounding peaks.', campAltitude: 4200 },
      { day: 6, title: 'Samiti Lake to Goechala & Return', description: 'The triumphant push to Goechala viewpoint at 4940m.', campAltitude: 4200 },
      { day: 7, title: 'Return Journey Begins — Samiti to Kokchurung', description: 'Begin the long descent back through the wilderness.', campAltitude: 3860 },
      { day: 8, title: 'Kokchurung to Tshoka', description: 'Trek back through the magical rhododendron forests.', campAltitude: 3050 },
      { day: 9, title: 'Tshoka to Yuksom', description: 'Final descent back to the trailhead at Yuksom.', campAltitude: 1780 }
    ],
    inclusions: ['All accommodation', 'Meals', 'Permits (national park)', 'Guide & porters', 'Safety equipment'],
    exclusions: ['Flights/travel to Bagdogra', 'Inner Line Permit', 'Personal expenses', 'Insurance'],
    avgRating: 4.9,
  },
  {
    _id: '7',
    slug: 'chadar-trek',
    name: 'Chadar Trek',
    region: 'Ladakh',
    state: 'Ladakh',
    difficulty: 'Extreme',
    duration: 9,
    maxAltitude: 3400,
    maxAltitudeFt: 11155,
    price: 24000,
    featured: false,
    shortDesc: 'Walk on the frozen Zanskar river through dramatic ice canyons in temperatures of -25°C.',
    description: 'The Chadar Trek is one of India\'s most dramatic winter expeditions — walking on the frozen Zanskar river (chadar means "sheet" in Hindi) through narrow gorges with towering frozen waterfalls, at temperatures that plunge to -25°C.',
    highlights: [
      'Walk on a frozen river at -25°C',
      'Dramatic ice canyon formations',
      'Frozen waterfalls up to 40m high',
      'Authentic Ladakhi cave camping',
      'Complete disconnection from civilization'
    ],
    images: [{ url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782209552/treks/zfn8iiytjzdjm0wnoptd.jpg', caption: 'Trekkers on the frozen Zanskar river' }],
    bestSeason: ['January', 'February'],
    elevationProfile: [
      { km: 0, altM: 3050 }, { km: 5, altM: 3100 }, { km: 12, altM: 3150 },
      { km: 19, altM: 3200 }, { km: 26, altM: 3250 }, { km: 33, altM: 3300 },
      { km: 40, altM: 3400 }, { km: 46, altM: 3350 }, { km: 52, altM: 3050 }
    ],
    itinerary: [
      { day: 1, title: 'Leh Acclimatization', description: 'Arrive Leh (3500m). Mandatory acclimatization day — gentle sightseeing.', campAltitude: 3500 },
      { day: 2, title: 'Leh Acclimatization & Gear Check', description: 'Full gear check, briefing, and second acclimatization day.', campAltitude: 3500 },
      { day: 3, title: 'Chilling to Tilat Sumdo', description: 'First day on the frozen Zanskar. Camp in a cave at Tilat Sumdo.', campAltitude: 3100 },
      { day: 4, title: 'Tilat Sumdo to Gyalpo', description: 'Trek through the dramatic Zanskar gorge canyon.', campAltitude: 3200 },
      { day: 5, title: 'Gyalpo to Tibb Cave', description: 'The most spectacular section with massive frozen waterfalls.', campAltitude: 3300 },
      { day: 6, title: 'Tibb Cave to Naerak', description: 'Reach Naerak, the turnaround point at 3400m.', campAltitude: 3400 },
      { day: 7, title: 'Naerak to Tibb Cave (Return)', description: 'Begin the return journey on the frozen river.', campAltitude: 3300 },
      { day: 8, title: 'Tibb Cave to Chilling', description: 'Final push back to Chilling and drive to Leh.', campAltitude: 3500 }
    ],
    inclusions: ['All accommodation (caves/camps)', 'All meals', 'Expert Chadar guide', 'All permits', 'Emergency evacuation protocol', 'Crampons (rental)'],
    exclusions: ['Flights to Leh', 'Personal cold-weather gear', 'Travel insurance (mandatory)', 'Altitude sickness medication'],
    avgRating: 4.7,
  },
  {
    _id: '8',
    slug: 'pin-parvati-pass',
    name: 'Pin Parvati Pass',
    region: 'Himachal Pradesh',
    state: 'Himachal Pradesh',
    difficulty: 'Extreme',
    duration: 11,
    maxAltitude: 5319,
    maxAltitudeFt: 17451,
    price: 28000,
    featured: false,
    shortDesc: 'One of India\'s most challenging crossover treks — from the lush Parvati valley to the barren Pin valley.',
    description: 'Pin Parvati Pass is among the most challenging and remote treks in India. The crossing at 5319m connects the verdant Parvati valley in Kullu to the cold desert of Pin valley in Spiti — a journey through two completely different worlds.',
    highlights: [
      'Crossing at 5319m — highly technical',
      'Transition from Kullu green to Spiti desert',
      'Glacier crossing experience',
      'Complete wilderness — no mobile network',
      'Views across Spiti, Kinnaur and Kullu Himalayas'
    ],
    images: [{ url: 'https://res.cloudinary.com/dirsimqmr/image/upload/v1782209557/treks/wkpqcxwbgyjhvetr2ttu.jpg', caption: 'The glaciated Pin Parvati Pass crossing' }],
    bestSeason: ['July', 'August', 'September'],
    elevationProfile: [
      { km: 0, altM: 2050 }, { km: 8, altM: 2600 }, { km: 16, altM: 3200 },
      { km: 23, altM: 3800 }, { km: 30, altM: 4400 }, { km: 36, altM: 4900 },
      { km: 39, altM: 5319 }, { km: 46, altM: 4200 }, { km: 54, altM: 3500 },
      { km: 62, altM: 2980 }
    ],
    itinerary: [
      { day: 1, title: 'Barsheni to Kalga', description: 'Trek from road end at Barsheni through forest to Kalga village.', campAltitude: 2440 },
      { day: 2, title: 'Kalga to Tunda Bhuj', description: 'Trek along the Parvati river gorge through thick forest.', campAltitude: 2800 },
      { day: 3, title: 'Tunda Bhuj to Odi Thach', description: 'Landscape opens up, river crossings begin.', campAltitude: 3300 },
      { day: 4, title: 'Odi Thach to Thakur Kuan', description: 'High camp below the glacier zone.', campAltitude: 3900 },
      { day: 5, title: 'Thakur Kuan to Mantalai Lake', description: 'Sacred lake at 4150m, source of the Parvati river.', campAltitude: 4150 },
      { day: 6, title: 'Mantalai to Base of Pass', description: 'Technical glacier approach to high camp below the pass.', campAltitude: 4750 },
      { day: 7, title: 'Cross Pin Parvati Pass (5319m)', description: 'Summit day — cross the glaciated pass into the Pin valley.', campAltitude: 4500 },
      { day: 8, title: 'Descent through Pin Valley', description: 'Dramatic descent through Spiti moonscape to Pin valley.', campAltitude: 3800 },
      { day: 9, title: 'Continue Descent — Mud Village', description: 'Trek to Mud village, the first settlement in Pin valley.', campAltitude: 3690 },
      { day: 10, title: 'Mud to Kaza', description: 'Drive through the stunning Pin valley to Kaza, Spiti headquarters.', campAltitude: 3800 }
    ],
    inclusions: ['All accommodation', 'All meals', 'Expert high-altitude guide', 'All permits', 'Technical gear', 'Emergency protocol'],
    exclusions: ['Travel to Barsheni / from Kaza', 'Personal technical gear (ice axe, crampons)', 'Comprehensive travel insurance (mandatory)'],
    avgRating: 4.8,
  },
  {
    _id: '9',
    slug: 'dayara-bugyal',
    name: 'Dayara Bugyal',
    region: 'Uttarakhand',
    state: 'Uttarakhand',
    difficulty: 'Easy',
    duration: 6,
    maxAltitude: 3605,
    maxAltitudeFt: 11830,
    price: 9000,
    featured: false,
    shortDesc: 'One of the most beautiful alpine meadows in India, perfect for beginners.',
    description: 'Dayara Bugyal is undoubtedly one of the most beautiful alpine meadows in India. The trek is perfect for beginners and offers stunning views of the Gangotri range, including Bandarpoonch and Black Peak. Please note: The distance between campsites may vary by 100 meters depending the weather conditions and the route you take. The altitude may also vary by 100 feet for similar reasons.',
    highlights: [
      'Stunning alpine meadows spanning miles',
      'Breathtaking views of the Gangotri range',
      'Perfect introduction to Himalayan trekking',
      'Beautiful old growth forest sections'
    ],
    mapImage: '/assets/mapes/dayara-bugyal.jpeg',
    images: [
      { url: '/assets/treks/treks/banner_dayarabugyal.jpg', caption: 'Dayara Bugyal Banner' },
      { url: '/assets/treks/treks/WhatsApp%20Image%202026-06-23%20at%2013.23.09.jpeg', caption: 'Dayara Bugyal Trail' },
      { url: '/assets/treks/treks/WhatsApp%20Image%202026-06-23%20at%2013.23.11.jpeg', caption: 'Dayara Bugyal Meadow' },
      { url: '/assets/treks/treks/WhatsApp%20Image%202026-06-23%20at%2013.23.14.jpeg', caption: 'Dayara Bugyal View' },
      { url: '/assets/treks/treks/WhatsApp%20Image%202026-06-23%20at%2013.43.17.jpeg', caption: 'Dayara Bugyal Campsite' },
      { url: '/assets/treks/treks/WhatsApp%20Image%202026-06-23%20at%2013.43.24.jpeg', caption: 'Dayara Bugyal Landscape' }
    ],
    bestSeason: ['May', 'June', 'September', 'October', 'November'],
    elevationProfile: [
      { km: 0, altM: 2176 }, { km: 4.5, altM: 2935 }, { km: 7, altM: 3204 },
      { km: 16.5, altM: 2799 }, { km: 20.5, altM: 2176 }
    ],
    itinerary: [
      { day: 1, title: 'Drive From Dehradun to Raithal', description: 'Drive Distance: 185 km | Drive Duration: 9 hours | Pick up point: Asli Pappu Da Dhaba, Dehradun at 6.30 am. Transport cost is Rs. 1300/- per trekker (one-way).', campAltitude: 2176 },
      { day: 2, title: 'Trek from Raithal to Gui', description: 'Trek Distance: 4.5 km | Trek Duration: 5 hours | Altitude Gain: 7,142 ft to 9,630 ft', campAltitude: 2935 },
      { day: 3, title: 'Trek from Gui to Chilapada', description: 'Trek Distance: 2.5 km | Trek Duration: 2-3 hours | Altitude Gain: 9,630 ft to 10,515 ft', campAltitude: 3204 },
      { day: 4, title: 'Trek from Chilpada to Nayata via Dayara Top', description: 'Trek Distance: 9.5 km | Trek Duration: 6-7 hours | Altitude Gain and Loss: 10,515 ft to 9,186 ft via 11,830 ft', campAltitude: 2799 },
      { day: 5, title: 'Trek from Nayata to Raithal', description: 'Trek Distance: 4 km | Trek Duration: 4-5 hours | Altitude Loss: 9,186 ft to 7,142 ft', campAltitude: 2176 },
      { day: 6, title: 'Drive back from Raithal to Dehradun', description: 'Drive distance: 185 km | Drive Duration: 9 hours | Drop off point: Asli Pappu Da Dhaba, Dehradun by 6 pm. Transport cost is Rs. 1300/- per trekker (one-way).', campAltitude: 0 }
    ],
    inclusions: ['Accommodation', 'All meals on trek', 'Certified guide', 'Permit', 'Safety equipment'],
    exclusions: ['Travel to Dehradun', 'Personal expenses', 'Travel insurance', 'Transport to basecamp'],
    avgRating: 4.9,
  },
  {
    _id: 'gaumukh-tapovan-01',
    slug: 'gaumukh-tapovan',
    name: 'Gaumukh Tapovan Trek',
    region: 'Uttarakhand',
    state: 'Uttarakhand',
    difficulty: 'Moderate',
    duration: 5,
    durationLabel: '5 Days / 4 Nights',
    maxAltitude: 4100,
    maxAltitudeFt: 13452,
    price: 18000,
    featured: true,
    shortDesc: 'Discover the Birthplace of India’s Most Sacred River',
    description: `The Gaumukh Tapovan Trek is among the most extraordinary journeys in the Indian Himalayas, combining breathtaking alpine landscapes with centuries of spiritual heritage. Located inside Gangotri National Park in Uttarakhand, the trek leads to Gaumukh, the snout of the mighty Gangotri Glacier and the physical source of the Bhagirathi River, which later becomes the holy River Ganga.\n\nUnlike many Himalayan treks that are purely adventure-oriented, the Gaumukh Tapovan Trek offers a rare blend of spirituality, mythology, glacial exploration, and high-altitude mountaineering. Every step along the trail carries historical significance while revealing some of the most spectacular mountain scenery in India.\n\n⸻\n\nWhy is Gaumukh So Sacred?\n\nThe word Gaumukh literally means “Cow’s Mouth” because the glacier’s snout once resembled the face of a cow. Situated at an altitude of 4,100 metres (13,452 ft), this glacier marks the origin of the Bhagirathi River, one of the primary headstreams of the River Ganga.\n\nFor millions of Hindus, the Ganga is not merely a river but a living goddess symbolizing purity, life, and liberation. Pilgrims travel from across the country to witness the sacred glacier where this divine river begins its journey from the Himalayas to the plains of India.\n\n⸻\n\nA Journey Beyond Adventure\n\nStarting from the holy town of Gangotri, the trail gradually follows the roaring Bhagirathi River through ancient forests, dramatic valleys, glacial moraines, and wide Himalayan landscapes. Along the route, trekkers experience an ever-changing environment where dense pine forests slowly give way to barren alpine terrain and towering snow-covered peaks.\n\nThe trek eventually reaches Gaumukh Glacier, where the icy waters emerge from beneath massive walls of ancient ice. Many trekkers continue further towards Tapovan, a magnificent high-altitude meadow renowned for its panoramic views of Mount Shivling, Meru Peak, and the Bhagirathi mountain range.\n\nFor experienced trekkers, Tapovan also serves as the gateway to expeditions towards Nandanvan, Vasuki Tal, and the challenging Kalindi Khal Pass, making the region one of the most important trekking hubs in the Garhwal Himalayas.\n\n⸻\n\nBhojbasa – The Most Beautiful Campsite on the Trek\n\nAmong all the campsites along the route, Bhojbasa is considered the most scenic and memorable. Located at approximately 3,800 metres (12,500 ft) beside the Bhagirathi River, it serves as the primary overnight halt before reaching Gaumukh.\n\nSurrounded by rugged Himalayan cliffs and snow-covered summits, Bhojbasa offers an atmosphere of complete peace and isolation. The campsite derives its name from the ancient Bhoj (Birch) trees, whose bark was historically used to write sacred Hindu scriptures.\n\nTrekkers camping here witness unforgettable Himalayan sunrises as the first golden rays illuminate Shivling and the Bhagirathi peaks. Evenings are equally magical, with glowing mountain silhouettes reflected across the glacial valley while the sound of the river echoes through the mountains.\n\nBeyond its natural beauty, Bhojbasa is also known for its spiritual atmosphere. Pilgrims, monks, and trekkers often meditate, chant prayers, or simply enjoy the silence before continuing towards Gaumukh.\n\n⸻\n\nRoute Overview\n\n* Starting Point: Gangotri (3,100 metres)\n* Destination: Gaumukh Glacier (4,100 metres)\n* Extension: Tapovan (4,463 metres)\n* One-way Trek Distance: Approximately 18 km to Gaumukh\n* Trail Type: Gradual ascent through forests, rocky terrain, glacier moraine, and alpine landscapes\n\nThe trail closely follows the Bhagirathi River, providing spectacular views throughout the journey. Every section reveals new landscapes ranging from lush valleys to barren glacial terrain.\n\n⸻\n\nGangotri Dham – The Spiritual Gateway\n\nBefore beginning the trek, every visitor passes through Gangotri Dham, one of the four sacred shrines of the Char Dham Yatra.\n\nSituated at an altitude of around 3,100 metres, the temple is dedicated to Goddess Ganga, who is worshipped as the divine mother of India. Although the physical source of the river lies further ahead at Gaumukh, Gangotri is traditionally regarded as the sacred place where Goddess Ganga descended to Earth.\n\nBuilt during the early eighteenth century by Amar Singh Thapa, the temple has remained one of the holiest pilgrimage destinations in the Himalayas for centuries.\n\nEvery year, thousands of devotees visit Gangotri to perform rituals, seek blessings, and begin the spiritual journey towards Gaumukh.\n\n⸻\n\nThe Legend of King Bhagirath\n\nAccording to Hindu mythology, King Bhagirath performed intense meditation to bring the heavenly River Ganga down to Earth so that the souls of his ancestors could attain salvation.\n\nMoved by his devotion, Goddess Ganga agreed to descend from heaven. However, her immense force threatened to destroy the Earth. Lord Shiva intervened by capturing the river in his matted locks before gently releasing her into the Himalayas.\n\nThe first sacred stream became the Bhagirathi River, named after King Bhagirath, eventually flowing from Gaumukh towards the plains as the holy River Ganga.\n\nThis timeless legend gives Gangotri and Gaumukh immense spiritual importance and continues to inspire millions of pilgrims every year.\n\n⸻\n\nHistory, Nature & Spirituality in One Journey\n\nFew Himalayan treks combine mythology, geography, history, and adventure as beautifully as the Gaumukh Tapovan Trek.\n\nAncient sages such as Swami Tapovan Maharaj and Swami Sundaranand spent decades meditating in these mountains, while generations of pilgrims have walked the same trail seeking spiritual peace.\n\nToday, trekkers come not only to witness the spectacular Gangotri Glacier but also to experience the profound silence, pristine wilderness, and towering Himalayan peaks that make this one of India’s most unforgettable trekking destinations.\n\nWhether you seek adventure, photography, mountaineering, or spiritual exploration, the Gaumukh Tapovan Trek offers a once-in-a-lifetime journey into the very heart of the Garhwal Himalayas.`,
    highlights: [
      'Discover the Birthplace of India’s Most Sacred River',
      'The Legend of King Bhagirath',
      'Gangotri Dham – The Spiritual Gateway',
      'Bhojbasa – The Most Beautiful Campsite on the Trek',
      'A Journey Beyond Adventure',
    ],
    images: [
      { url: '/assets/treksss/gomukh/gaumukh-trek.jpeg', caption: 'Gaumukh Tapovan Trek' }
    ],
    bestSeason: ['May', 'June', 'September', 'October'],
    elevationProfile: [
      { km: 0, altM: 3100 }, { km: 9, altM: 3800 }, { km: 18, altM: 4100 }, { km: 23, altM: 4463 }
    ],
    mapImage: '/assets/mapes/gaumukh.png',
    itinerary: [],
    inclusions: ['Accommodation (Tents/Hotel)', 'Complete Package from Dehradun To Dehradun'],
    exclusions: ['5% GST', 'Optional: ₹500 Backpack Offloading', 'Single Tent/Hotel Room occupancy on request, extra cost'],
    avgRating: 4.8,
    suitableFor: '10 to 60 years',
    distance: '36 kms',
    basecamp: 'Gangotri',
    accommodation: 'Tents/Hotel',
    pickup: 'Railway Station, Dehradun',
    dropoff: 'Railway Station, Dehradun',
    cloakroom: 'Available',
    offloading: 'Available'
  }
];

export const TREKS_MAP = Object.fromEntries(TREKS.map(t => [t.slug, t]));

export const FEATURED_TREKS = TREKS.filter(t => t.featured);
